# Generated by Django 5.1.3 on 2025-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('anime_id', models.CharField(max_length=255, verbose_name='anime')),
            ],
            options={
                'verbose_name': 'AnimeModel',
                'verbose_name_plural': 'AnimeModels',
                'db_table': 'anime',
            },
        ),
    ]
