# Generated by Django 5.1.3 on 2025-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='link',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='link',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True, verbose_name='link'),
        ),
    ]
