# Generated by Django 5.1.3 on 2025-02-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animemodel',
            options={'verbose_name': 'Animelar', 'verbose_name_plural': 'Animelar'},
        ),
        migrations.AlterModelOptions(
            name='episodemodel',
            options={'verbose_name': 'Anime qismlari', 'verbose_name_plural': 'Anime qismlari'},
        ),
    ]
