# Generated by Django 5.1.3 on 2025-03-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_animemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodemodel',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='anime.animemodel'),
        ),
    ]
