# Generated by Django 5.1.3 on 2025-03-02 13:48

import core.apps.anime.models.episode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_alter_episodemodel_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodemodel',
            name='id',
            field=models.CharField(default=core.apps.anime.models.episode.generate_random_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
